---
title: "QC sample correlation plot"
author:
- name: Xiaotao Shen (https://www.shenxt.info/)
date: "Created on 2021-12-04 and updated on `r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: no
  pdf_document:
    toc: no
vignette: >
  %\VignetteIndexEntry{qc_correlation}
  %\VignettePackage{massqc}
  % \VignetteEngine{knitr::rmarkdown}
  % \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = TRUE,
  out.width = "100%"
)
```

# **Data preparation**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
library(massdataset)
library(tidyverse)
library(massqc)
data("sample_info", package = "massdataset")
data("expression_data", package = "massdataset")
data("variable_info", package = "massdataset")
object =
  create_mass_dataset(
    expression_data = expression_data,
    sample_info = sample_info,
    variable_info = variable_info
  )
object
```

# **QC correlation plot**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
object %>%
  massqc_sample_correlation()

object %>%
  massqc_sample_correlation()

object %>%
  activate_mass_dataset(what = "sample_info") %>%
  filter(class == "QC") %>%
  massqc_sample_correlation()

object %>%
  massqc_sample_correlation(lab = TRUE)

object %>%
  massqc_sample_correlation(lab = TRUE, type = "upper")
```

# **Session information**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
sessionInfo()
```
