---
title: "Boxplot for each sample"
author:
- name: Xiaotao Shen (https://www.shenxt.info/)
date: "Created on 2021-12-04 and updated on `r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: no
  pdf_document:
    toc: no
vignette: >
  %\VignetteIndexEntry{massqc_sample_boxplot}
  %\VignettePackage{massqc}
  % \VignetteEngine{knitr::rmarkdown}
  % \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = TRUE,
  out.width = "100%"
)
```

# **Data preparation**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
library(massdataset)
library(tidyverse)
library(massqc)
data("sample_info", package = "massdataset")
data("expression_data", package = "massdataset")
data("variable_info", package = "massdataset")
object =
  create_mass_dataset(
    expression_data = expression_data,
    sample_info = sample_info,
    variable_info = variable_info
  )
object
```

# **Sample boxplot**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
 object %>%
   massqc_sample_boxplot()

 object %>%
   log(10) %>%
   massqc_sample_boxplot()

 object %>%
   log(10) %>%
   massqc_sample_boxplot(color_by = "class")

 object %>%
   log(10) %>%
   massqc_sample_boxplot(fill_by = "class") +
   ggsci::scale_fill_lancet()

 object %>%
   log(10) %>%
   massqc_sample_boxplot(
     fill_by = "class",
     color_by = "class",
     point = TRUE,
     point_alpha = 0.3
   ) +
   ggsci::scale_fill_lancet()

 object %>%
   log(10) %>%
   massqc_sample_boxplot(color_by = "class",
                  point = TRUE,
                  point_alpha = 0.3) +
   ggsci::scale_color_lancet()
```

# **Session information**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
sessionInfo()
```
